name: Build and Deploy Docker image
  
on:
  push:
    branches:
      - sandbox
    paths-ignore:
      - '**.md'
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-24.04
    concurrency: # Cancel redundant builds
      group: ${{ github.workflow }}-${{ github.ref }}
      cancel-in-progress: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=VERSION::$VERSION"

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ./docker
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            ghcr.io/${{ github.repository }}/dmm:latest
            ghcr.io/${{ github.repository }}/dmm:${{ steps.version.outputs.version }}
            lusky3/dmm:latest
            lusky3/dmm:${{ steps.version.outputs.VERSION }}
          outputs: |
            type=image,name=target,annotation-index.org.opencontainers.image.title=Debrid Media Manager
            type=image,name=target,annotation-index.org.opencontainers.image.description=Debrid Media Manager
            type=image,name=target,annotation-index.org.opencontainers.image.source=https://github.com/${{ github.repository }}/dmm.git
            type=image,name=target,annotation-index.org.opencontainers.image.version=${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.description=Debrid Media Manager
            org.opencontainers.image.title=Debrid Media Manager
            org.opencontainers.image.version=${{ steps.version.outputs.version }}
