name: Build Tor

on:
  push:
    branches:
      - sandbox
    paths:
      - '/docker/Dockerfile.tor'
      - '/docker/renew-tor.sh'
  workflow_dispatch:

jobs:
  tor-build-and-push:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Read version from package.json
        id: version
        run: |
          VERSION=$(node -p "require('./package.json').version")
          echo "::set-output name=VERSION::$VERSION"

      - name: Build and push Docker image
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: ./docker/
          file: Dockerfile.tor
          push: true
          platforms: linux/amd64,linux/arm64
          cache-from: type=gha
          cache-to: type=gha,mode=max
          tags: |
            lusky3/tor:latest
            lusky3/tor:${{ steps.version.outputs.VERSION }}
            ghcr.io/${{ github.repository }}/tor:latest
            ghcr.io/${{ github.repository }}/tor:${{ steps.version.outputs.version }}
          outputs: |
            type=image,name=target,annotation-index.org.opencontainers.image.title=Tor
            type=image,name=target,annotation-index.org.opencontainers.image.description=Tor
            type=image,name=target,annotation-index.org.opencontainers.image.source=https://github.com/${{ github.repository }}/dmm.git
            type=image,name=target,annotation-index.org.opencontainers.image.version=${{ steps.version.outputs.version }}
          labels: |
            org.opencontainers.image.description=Tor
            org.opencontainers.image.title=Tor
            org.opencontainers.image.version=${{ steps.version.outputs.version }}


